-- MySQL Script generated by MySQL Workbench
-- sex 15 jan 2021 23:29:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema SpotifyClone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SpotifyClone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SpotifyClone` ;

-- -----------------------------------------------------
-- Table `SpotifyClone`.`Planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`Planos` (
  `plano_id` INT NOT NULL AUTO_INCREMENT,
  `plano` VARCHAR(45) NOT NULL,
  `valor_plano` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`plano_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`Usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `plano_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_plano_idx` (`plano_id` ASC) VISIBLE,
  CONSTRAINT `fk_plano`
    FOREIGN KEY (`plano_id`)
    REFERENCES `SpotifyClone`.`Planos` (`plano_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`Artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`Artistas` (
  `artista_id` INT NOT NULL AUTO_INCREMENT,
  `artista` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`artista_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`Albuns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`Albuns` (
  `album_id` INT NOT NULL AUTO_INCREMENT,
  `album` VARCHAR(45) NOT NULL,
  `artista_id` INT NOT NULL,
  PRIMARY KEY (`album_id`),
  INDEX `fk_Albuns_Artista1_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `fk_Albuns_Artista1`
    FOREIGN KEY (`artista_id`)
    REFERENCES `SpotifyClone`.`Artistas` (`artista_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`Musicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`Musicas` (
  `musica_id` INT NOT NULL AUTO_INCREMENT,
  `cancoes` VARCHAR(100) NOT NULL,
  `album_id` INT NOT NULL,
  PRIMARY KEY (`musica_id`),
  INDEX `fk_Musicas_Albuns1_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `fk_Musicas_Albuns1`
    FOREIGN KEY (`album_id`)
    REFERENCES `SpotifyClone`.`Albuns` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`historico_de_reproducoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`historico_de_reproducoes` (
  `historico_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `musica_id` INT NOT NULL,
  PRIMARY KEY (`historico_id`),
  INDEX `fk_historico_de_reproducoes_Usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_historico_de_reproducoes_Musicas1_idx` (`musica_id` ASC) VISIBLE,
  CONSTRAINT `fk_historico_de_reproducoes_Usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `SpotifyClone`.`Usuarios` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_de_reproducoes_Musicas1`
    FOREIGN KEY (`musica_id`)
    REFERENCES `SpotifyClone`.`Musicas` (`musica_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SpotifyClone`.`Seguidores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`Seguidores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `artista_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Seguidores_Usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_Seguidores_Artista1_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `fk_Seguidores_Usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `SpotifyClone`.`Usuarios` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seguidores_Artista1`
    FOREIGN KEY (`artista_id`)
    REFERENCES `SpotifyClone`.`Artistas` (`artista_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO SpotifyClone.Planos(plano, valor_plano) VALUES ('gratuito', 0);
INSERT INTO SpotifyClone.Planos(plano, valor_plano) VALUES ('familiar', 7.99);
INSERT INTO SpotifyClone.Planos(plano, valor_plano) VALUES ('universitário', 5.99);

INSERT INTO SpotifyClone.Artistas(artista) VALUES ('Walter Phoenix');
INSERT INTO SpotifyClone.Artistas(artista) VALUES ('Peter Strong');
INSERT INTO SpotifyClone.Artistas(artista) VALUES ('Lance Day');
INSERT INTO SpotifyClone.Artistas(artista) VALUES ('Freedie Shannon');

INSERT INTO SpotifyClone.Usuarios(usuario, idade, plano_id) VALUES ('Thati', 23, 1);
INSERT INTO SpotifyClone.Usuarios(usuario, idade, plano_id) VALUES ('Cintia', 35, 2);
INSERT INTO SpotifyClone.Usuarios(usuario, idade, plano_id) VALUES ('Bill', 20, 3);
INSERT INTO SpotifyClone.Usuarios(usuario, idade, plano_id) VALUES ('Roger', 45, 1);

INSERT INTO SpotifyClone.Albuns(album, artista_id) VALUES ('Envious', 1);
INSERT INTO SpotifyClone.Albuns(album, artista_id) VALUES ('Exuberant', 1);
INSERT INTO SpotifyClone.Albuns(album, artista_id) VALUES ('Hallowed Steam', 2);
INSERT INTO SpotifyClone.Albuns(album, artista_id) VALUES ('Incandescent', 3);
INSERT INTO SpotifyClone.Albuns(album, artista_id) VALUES ('Temporary Culture', 4);

INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Soul For Us', 1);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Reflections Of Magic', 1);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Dance With Her Own', 1);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Time Fireworks', 2);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Troubles Of My Inner Fire', 2);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Magic Circus', 3);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Honey, So Do I', 3);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ("Sweetie, Let's Go Wild", 3);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('She Knows', 3);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Fantasy For Me', 4);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Celebration Of More', 4);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Rock His Everything', 4);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Home Forever', 4);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Diamond Power', 4);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ("Honey, Let's Be Silly", 4);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Thang Of Thunder', 5);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Words Of Her Life', 5);
INSERT INTO SpotifyClone.Musicas(cancoes, album_id) VALUES ('Without My Streets', 5);

INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (1, 1);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (1, 6);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (1, 14);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (1, 16);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (2, 13);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (2, 17);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (2, 2);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (2, 15);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (3, 5);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (3, 16);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (3, 6);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (4, 3);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (4, 18);
INSERT INTO SpotifyClone.historico_de_reproducoes(usuario_id, musica_id) VALUES (4, 11);

INSERT INTO SpotifyClone.Seguidores(usuario_id, artista_id) VALUES (1, 4);
INSERT INTO SpotifyClone.Seguidores(usuario_id, artista_id) VALUES (1, 3);
INSERT INTO SpotifyClone.Seguidores(usuario_id, artista_id) VALUES (1, 1);
INSERT INTO SpotifyClone.Seguidores(usuario_id, artista_id) VALUES (2, 1);
INSERT INTO SpotifyClone.Seguidores(usuario_id, artista_id) VALUES (2, 3);
INSERT INTO SpotifyClone.Seguidores(usuario_id, artista_id) VALUES (3, 1);
INSERT INTO SpotifyClone.Seguidores(usuario_id, artista_id) VALUES (3, 2);
INSERT INTO SpotifyClone.Seguidores(usuario_id, artista_id) VALUES (4, 4);
